version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"    # Pour HTTP
      - "443:443"  # Pour HTTPS
    depends_on:
      - app

